root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parserOptions:
  project: tsconfig.dev.json
  ecmaVersion: 11
  sourceType: module
env:
  es2020: true
  node: true
rules:
  no-array-constructor: error
  no-caller: error
  no-dupe-class-members: off
  '@typescript-eslint/no-dupe-class-members': error
  no-empty-function: off
  '@typescript-eslint/no-empty-function': off
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-parens: off
  '@typescript-eslint/no-extra-parens': error
  no-implied-eval: error
  no-invalid-this: off
  '@typescript-eslint/no-invalid-this': error
  no-iterator: error
  no-labels: error
  no-label-var: error
  no-lone-blocks: error
  no-loop-func: off
  '@typescript-eslint/no-loop-func': error
  no-multi-spaces: error
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-wrappers: error
  no-octal-escape: error
  no-proto: error
  no-redeclare: off
  '@typescript-eslint/no-redeclare': error
  no-return-assign: error
  no-script-url: error
  no-sequences: error
  no-shadow: off
  '@typescript-eslint/no-shadow': error
  no-throw-literal: off
  '@typescript-eslint/no-throw-literal': error
  no-trailing-spaces: error
  no-undef-init: error
  no-unused-expressions: off
  '@typescript-eslint/no-unused-expressions': error
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - error
    - ignoreRestSiblings: true
  no-use-before-define:
    - error
    - nofunc
  no-useless-constructor: off
  '@typescript-eslint/no-useless-constructor': error
  brace-style: off
  '@typescript-eslint/brace-style':
    - error
    - 1tbs
    - allowSingleLine: true
  comma-dangle: off
  '@typescript-eslint/comma-dangle':
    - error
    - 'always-multiline'
  comma-spacing: off
  '@typescript-eslint/comma-spacing': error
  camelcase: warn
  consistent-return: error
  curly:
    - error
    - all
  default-param-last: off
  '@typescript-eslint/default-param-last': error
  dot-notation: off
  '@typescript-eslint/dot-notation':
    - error
    - allowIndexSignaturePropertyAccess: true
  eol-last: error
  eqeqeq: error
  func-call-spacing": off
  '@typescript-eslint/func-call-spacing': error
  keyword-spacing": off
  '@typescript-eslint/keyword-spacing': error
  key-spacing: error
  new-cap: error
  new-parens: error
  quotes: off
  '@typescript-eslint/quotes':
    - error
    - single
  semi: off
  '@typescript-eslint/semi': error
  semi-spacing: error
  space-infix-ops: off
  '@typescript-eslint/space-infix-ops':
    - error
    - int32Hint: false
  space-unary-ops:
    - error
    - words: true
      nonwords: false
  strict: error
  yoda: error


      
